# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Check Py_ENABLE_SHARED
      run: python3 -c "import distutils.sysconfig, sys, os; import pprint;pprint.pprint(distutils.sysconfig.get_config_vars()); print(hasattr(sys, 'getandroidapilevel')); print(sys.platform); pprint.pprint(os.environ); print(distutils.sysconfig.get_config_var('ANDROID_API_LEVEL')); print(distutils.sysconfig.get_config_var('MACHDEP'))"
